name: Deploy to Scaleway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: devops
    env:
      SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
      SCW_DEFAULT_REGION: ${{ secrets.SCW_DEFAULT_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: back
        run: npm i

      - name: Build backend Docker image
        run: docker build -t rg.fr-par.scw.cloud/YOUR_NAMESPACE/back:latest ./back

      - name: Log in to Scaleway Container Registry
        run: echo ${{ secrets.SCW_SECRET_KEY }} | docker login rg.fr-par.scw.cloud -u ${{ secrets.SCW_ACCESS_KEY }} --password-stdin

      - name: Push backend Docker image
        run: docker push rg.fr-par.scw.cloud/YOUR_NAMESPACE/back:latest

      - name: Deploy backend container (Scaleway CLI)
        uses: scaleway/action-scw@v0.0.2
        with:
          args: container container create image=rg.fr-par.scw.cloud/YOUR_NAMESPACE/back:latest max-scale=1 cpu-limit=100 memory-limit=128 private-network-id=6aab9b1f-f374-4797-a5f3-efd53d9167c2

      - name: Get backend URL
        id: get_back_url
        uses: scaleway/action-scw@v0.0.2
        with:
          args: container container get YOUR_BACK_CONTAINER_ID -o json

      - name: Set BACK_URL env
        run: |
          echo "BACK_URL=$(echo '${{ steps.get_back_url.outputs.stdout }}' | jq -r '.status.url')" >> $GITHUB_ENV

      - name: Install frontend dependencies
        working-directory: front
        run: npm i

      - name: Build frontend Docker image with backend URL
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ env.BACK_URL }} \
            -t rg.fr-par.scw.cloud/YOUR_NAMESPACE/front:latest ./front

      - name: Push frontend Docker image
        run: docker push rg.fr-par.scw.cloud/YOUR_NAMESPACE/front:latest

      - name: Deploy frontend container (Scaleway CLI)
        uses: scaleway/action-scw@v0.0.2
        with:
          args: container container create image=rg.fr-par.scw.cloud/YOUR_NAMESPACE/front:latest max-scale=1 cpu-limit=100 memory-limit=128 private-network-id=6aab9b1f-f374-4797-a5f3-efd53d9167c2
