name: Deploy to Scaleway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: devops
    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
      SCW_DEFAULT_REGION: ${{ secrets.SCW_DEFAULT_REGION }}
      SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: back
        run: npm i

      - name: Build backend Docker image
        run: docker build -t rg.fr-par.scw.cloud/namespace-nathan-bertaud/back:latest ./back

      - name: Log in to Scaleway Container Registry
        run: echo ${{ secrets.SCW_SECRET_KEY }} | docker login rg.fr-par.scw.cloud -u ${{ secrets.SCW_ACCESS_KEY }} --password-stdin

      - name: Push backend Docker image
        run: docker push rg.fr-par.scw.cloud/namespace-nathan-bertaud/back:latest

      - name: Deploy backend container (Scaleway CLI)
        uses: scaleway/action-scw@v0.0.2
        with:
          args: container container create name=backend-container-nathan-bertaud port=3000 registry-image=rg.fr-par.scw.cloud/namespace-nathan-bertaud/back:latest max-scale=1 cpu-limit=100 memory-limit=256 namespace-id=8284e924-797a-428b-8329-1bb065f9cd89

      - name: Get backend URL
        id: get_backend_url
        run: |
          BACK_CONTAINER_ID=$(scw container container list name=backend-container-nathan-bertaud -o json | jq -r '.[0].id')
          BACK_URL=$(scw container container get $BACK_CONTAINER_ID -o json | jq -r '.domain_name')
          echo "BACK_URL=$BACK_URL"
          echo "BACK_URL=$BACK_URL" >> $GITHUB_ENV
          echo "::set-output name=url::$BACK_URL"
      - name: Install frontend dependencies
        working-directory: front
        run: npm i

      - name: Build frontend Docker image with backend URL
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ env.BACK_URL }} \
            -t rg.fr-par.scw.cloud/namespace-nathan-bertaud/front:latest ./front

      - name: Push frontend Docker image
        run: docker push rg.fr-par.scw.cloud/namespace-nathan-bertaud/front:latest

      - name: Deploy frontend container (Scaleway CLI)
        uses: scaleway/action-scw@v0.0.2
        with:
          args: container container create name=frontend-container port=80 registry-image=rg.fr-par.scw.cloud/namespace-nathan-bertaud/front:latest max-scale=1 cpu-limit=100 memory-limit=128 namespace-id=8284e924-797a-428b-8329-1bb065f9cd89